{{- if .Values.ingress }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx-revproxy
  {{- if .Values.ingress.class }}
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
  {{- end }}
spec:
  tls:
    - hosts:
      - {{ .Values.ingress.host }}
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: nginx-revproxy
          servicePort: {{ .Values.service.httpPort }}
{{- end }}
