apiVersion: v1
kind: Secret
metadata:
  name: cloud-top-env
data:
  USER_HOME: {{ .Values.apps.CLOUD_TOP_USER_HOME }}
  USER_NAME: {{ .Values.apps.CLOUD_TOP_USER_NAME }}
  VNC_PW: {{ .Values.apps.CLOUD_TOP_VNC_PW }}
