apiVersion: v1
data:
  # /usr/src/inst-mgmt is default location if db is created in the container.
  # OAUTH_DB_DIR: /usr/src/inst-mgmt
  # /var/lib/sqlite3 is used for PVC mount point.
  OAUTH_DB_DIR: /var/lib/sqlite3
  OAUTH_DB_FILE: DATABASE.sqlite3
  ACCOUNT_DEFAULT_HTTP_PROTOCOL: https
  TYCHO_URL: http://tycho-api:8099
  DEV_PHASE: "prod"
kind: ConfigMap
metadata:
  labels:
  name: csappstore-env
